Expecting ',' delimiter: line 231 column 6 (char 8971)Traceback (most recent call last):
  File "D:\Perfil\Documentos\validatorsGesi\index.py", line 900, in <module>
    areas = cargar_areas()
            ^^^^^^^^^^^^^^
  File "D:\Perfil\Documentos\validatorsGesi\index.py", line 52, in cargar_areas
    return json.load(archivo)
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Gesi-Educativo\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Gesi-Educativo\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Gesi-Educativo\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Gesi-Educativo\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 231 column 6 (char 8971)
